[REVISE] 第8章テキストの修正とリンクと図の挿入
sunagi/DAO-Book pull request #8
Opened 2024-10-15 07:02 UTC by sunagi

第8章に以下の修正をしました。

第8章のテキストの修正
元記事（Biz記事）内でリンクが張られているテキスト部分にリンクを追加
図の挿入

2024-10-15 13:08 UTC, tspringk requested changes
@sunagi 
細かい指摘ですが、ご確認をお願いします！

2024-10-15 13:08 UTC, tspringk commented on chapters/chapter8.re
> +//image[html/chap08_01][Copyright © 2022 W3C® (MIT, ERCIM, Keio, Beihang)]
Re:VIEWのimageタグは、htmlディレクトリまで自動でたどるので不要のようです。
エラーではないのですが、rake epub 時にwarningが表示されます。

html/chap08_01
↓
chap08_01

2024-10-15 13:08 UTC, tspringk commented on chapters/chapter8.re
> +//image[html/chap08_02][開発ステップ]
Re:VIEWのimageタグは、htmlディレクトリまで自動でたどるので不要のようです。
エラーではないのですが、rake epub 時にwarningが表示されます。

html/chap08_02
↓
chap08_02

2024-10-16 02:00 UTC, sunagi commented
@tspringk ありがとうございます。修正致しました。

2024-10-17 02:36 UTC, tspringk approved these changes
@sunagi ありがとうございます！問題ございません。

2024-10-17 03:26 UTC, merged